In [1]:
# python lists data

a = [1.0, 2.0, 1.0]

In [2]:
a[0]

1.0

In [3]:
a

[1.0, 2.0, 1.0]

In [5]:
import torch # torch모듈 임포트

a = torch.ones(3) # 크기가 3인 1차원 텐서를 만들고 값을 1로 채우기

b = torch.zeros(4)

In [6]:
b

tensor([0., 0., 0., 0.])

In [7]:
a

tensor([1., 1., 1.])

In [8]:
a[1]

tensor(1.)

In [9]:
a[2] = 2.0
a

tensor([1., 1., 2.])